### PR TITLE
Development

### PR DESCRIPTION
**Pull request by maryfelmendoza**
We made changes suggested and when we check the form, it is in the center. Let know us if is ok.
Thanks.

### CODE REVIEW

**Review by bolah2009 — CHANGES_REQUESTED** [review]
## Awesome Job Team :muscle:

### The [clone](https://raw.githack.com/maryfelmendoza/intuitproject/development/index.html) looks nice and used HTML Forms elements effectively. :100: 

### However, there is one more thing to do.
- Add linter: You need two files to make this work: 
   - `.stickler.yml` config file found [here](https://github.com/microverseinc/linters-config/blob/master/css/.stickler.yml) and 
   - `stylelint.config.js` file which is found [here](https://github.com/microverseinc/linters-config/blob/master/css/stylelint.config.js)
More details on setting up linter for HTML & CSS projects can be found [here](https://github.com/microverseinc/linters-config/tree/master/css)

> 
> Please do the following **steps in this order**:
> 
> 1. Install stickler-ci https://github.com/apps/stickler-ci
> 2. Enable stickler in your repo. You can do it [here](https://stickler-ci.com/).
> 3. In first commit of your feature branch add a copy of [.stickler.yml](./.stickler.yml) and [stylelint.config.js](./stylelint.config.js).
>     - **Remember** to use both files linked above
>     - **Remember** that `.stickler.yml` file name starts with a dot
> 4. When you open your first pull request you should see Stickler's report at `Checks` tab.
> 


- [Next Project] Use GitHubFlow: For HTML & CSS projects, use only one feature branch (e.g. `embedding-images-and-video`, `html-forms`, `responsive-design`, etc) and **do not merge any feature branch to master until it's been approved**.

-  [`REQUIRED`] Please add a descriptive readme file:  Add the assignment link, the project specification, link to clone page and source page, screenshots and other pieces of information that would describe the project.

> Remember about descriptive README file.`


Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### Note that comments tagged `OPTIONAL` are strongly recommended but not required to approve the project.

**Comment by maryfelmendoza** [comment]
We added linters

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Hi there team. 
Nice work adding the linter :clap: 
But it seems that in the last changes you moved the CSS file from its former location and forgot to update the information in the index.html file. Your page is without styles right now.
So there some changes that we need to make:

[REQUIRED]
Make the CSS work on your page again.

[REQUIRED]
Your project needs to have a descriptive readme file. You can create one with the project specifications, assignment, and cloned pages links.

Please make these changes and submit for code review again.

[FRIENDLY-REMAINDER]
**Use GitHubFlow: For HTML & CSS projects, use only one feature branch (e.g. embedding-images-and-video, html-forms, responsive-design, etc) and do not merge any feature branch to master until it's been approved.**

Happy coding team :clap:

**Comment by samgaco** [comment]
### Hi @maryfelmendoza and @zhuchini :vulcan_salute: 

### Great job :+1: just one more thing before we can give you the approval:

* Mint, quickbooks and turbotax should be text with logos at the left side
logointuit

and a suggestion:

* [OPTIONAL] You could improve the readme file adding your contacts, a live demo of the site or getting inspiration on example templates like[ this one.](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)

### Please :pray: submit for another code review once you are done with these changes! :muscle:

**Comment by zhumiku** [comment]
Hi @samgaco,

What do you mean the logo and text have to be on the left side?
Is it too close to the top right corner?

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Review by Torres-ssf — APPROVED** [review]
### Great job making these changes team :clap: 
I'm giving this project a :+1:
Go on and merge to master. And one more thing:

[Next Project] Use GitHubFlow: For HTML & CSS projects, use only **one** feature branch (e.g. embedding-images-and-video, html-forms, responsive-design, etc) and do not merge any feature branch to master until it's been approved. And as it's said on the pathwrite instructions, you should use a feature name on the branch instead of development.

Good luck with the next project team. Happy coding :computer:

**Pull request merged**
